/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NZCOVIDBadge } from "./NZCOVIDBadge";

export { NZCOVIDBadge__factory } from "./factories/NZCOVIDBadge__factory";
